### ISSUE TITLE
Distinguish inline code hyperlink

### ISSUE THREAD

**Issue by CosmicHorrorDev** [notgull/notgull.github.io#10]
(Love all your blog posts and work on `smol`)

Inline code hyperlinks and inline code both appear to use the same style, so it's hard to distinguish whether an inline code block is also a hyperlink. This is made worse by how common it is for the hyperlink to only include an inline code block with no other distinguishing text

**Comment by notgull** [comment]
Fixed this in https://git.sr.ht/~notgull/blog/commit/027c51a

By the way, this blog is hosted on [SourceHut](https://sr.ht/~notgull/blog/), so file future issues against there. I should really link to there in the README here...
